
regx <- function(x, ...) regex(x, ignore_case = TRUE, ...)
fixd <- function(x, ...) fixed(x, ignore_case = TRUE, ...)

pretty_history <- function(df) {
  df %>%
    mutate(
      Diagnosis = str_extract(Diagnosis, "[\\w\\s]+"),
      Diagnosis = if_else(is.na(Diagnosis), "none", Diagnosis),
      ds = History,
      qx = if_else(str_detect(Diagnosis, regx("none|below|unknown")) | (str_detect(`Admit Commments`, Diagnosis)) , `Admit Commments`, paste0(Diagnosis, "; ", `Admit Commments`)),
      
      qx = str_remove(qx, "Ordering(.*?)WHY"),
      qx = str_remove(qx, regx("CT.{1,20}?con(trast|$|\\s|[\\p{P}\\p{S}])")),
      qx = str_remove(qx, regx("CT.{1,20}?dose")),
      qx = str_remove(qx, regx("MR.{1,20}?con(trast|$|\\s|[\\p{P}\\p{S}])")),
      qx = str_remove(qx, regx("IV(.*?)contrast")),
      qx = str_remove(qx, regx("(^|\\s)W.{1,20}?con(trast|$|\\s|[\\p{P}\\p{S}])")),
      qx = str_remove(qx, regx("IV.{1,20}?con")),
      qx = str_remove(qx, regx("FOR\\s?FILE")),
      ds = str_remove(ds, regx("FOR\\s?FILE")),
      ds = str_remove(ds, regx("\\(CS:\\s?C?T?\\sCAT\\s\\w{0,4}\\)")),
      qx = str_remove(qx, regx("(^|\\s)STAT($|\\s|[\\p{P}\\p{S}])")),
      qx = str_remove(qx, regx("urgent ind:(.*?)($|[:,;\\.])")),
      
      ds = str_remove(ds, "\\[.*\\]"),
      qx = str_remove(qx, regx("(wet|stat) read")),
      qx = str_remove(qx, regx("attn:(.*?)")),
      qx = str_remove_all(qx, regx("(^|\\s)Please($|\\s|[\\p{P}\\p{S}])")),
      qx = str_remove_all(qx, regx("(^|\\s)pls($|\\s|[\\p{P}\\p{S}])")),
      
      ds = str_remove(ds, regx("\\sCIS($|\\s|[\\p{P}\\p{S}])")),
      ds = str_remove(ds, regx("\\sNOS($|\\s|[\\p{P}\\p{S}])")),
      
      qx = str_replace_all(qx, fixd("\\.br\\"), " "),
      qx = str_replace_all(qx, fixd("\\e e\\"), " "),
      qx = str_replace_all(qx, regx("(^|\\s)(FOR\\s?READ)($|\\s|[\\p{P}\\p{S}])"), "\\1Submitted outside study for evaluation of oncologic findings\\3"),
      ds = str_remove(ds, regx("(^|\\s)((FR)|(FOR\\s?READ|READ))($|\\s|[\\p{P}\\p{S}])")),
      qx = str_replace_all(qx, regx("dx($|\\s|[\\p{P}\\p{S}])"), "diagnosis "),
      qx = str_replace_all(qx, regx("(\\d){1,2}\\s?mo\\s"), "\\1 month"),
      
      qx = str_replace_all(qx, regx("(^|\\s)h(\\s|[\\p{P}\\p{S}]|\\/)?o(\\s|[\\p{P}\\p{S}])"), "\\1History of\\3"),
      ds = str_replace_all(ds, regx("(^|\\s)h(\\s|[\\p{P}\\p{S}]|\\/)?o(\\s|[\\p{P}\\p{S}])"), "\\1History of\\3"),
      qx = str_replace_all(qx, regx("(^|\\s)hx(\\s|[\\p{P}\\p{S}])"), "\\1History\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)hx(\\s|[\\p{P}\\p{S}])"), "\\1History\\2"),
      
      qx = str_replace_all(qx, regx("(\\d){1,3}\\smo(\\s|[\\p{P}\\p{S}])"), "\\1 months\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)c(\\s|[\\p{P}\\p{S}])?f(\\s|[\\p{P}\\p{S}])"), "\\1concern for\\3"),
      qx = str_replace_all(qx, regx("(^|\\s)f(\\s|[\\p{P}\\p{S}])?u($|\\s|[\\p{P}\\p{S}])"), "\\1Follow up\\3"),
      qx = str_replace_all(qx, regx("(^|\\s)Pt($|\\s|[\\p{P}\\p{S}])"), "\\1Patient\\2"),
      qx = str_replace_all(qx, fixd("Pre op"), "Preoperative evaluation"),
      qx = str_replace_all(qx, fixd("Post op"), "Postoperative evaluation"),
      ds = str_replace_all(ds, regx("Susp?\\s"), "Suspicious "),
      qx = str_replace_all(qx, regx("(^|\\s)n(\\s|[\\p{P}\\p{S}])v($|\\s|[\\p{P}\\p{S}])"), "\\1nausea and vomiting\\3"),
      
      qx = str_replace_all(qx, regx("eval$"), "Evaluate extent of disease"),
      qx = str_replace_all(qx, regx("r(\\s|[\\p{P}\\p{S}]|\\/)?o p(\\s|o)?d($|\\s|[\\p{P}\\p{S}])"), "Evaluate extent of disease\\3"),
      qx = str_replace_all(qx, regx("(^|\\s)eod($|\\s|[\\p{P}\\p{S}])"), "\\1Evaluate extent of disease\\2"),
      qx = str_replace_all(qx, regx("restag(e|ing)"), "Evaluate extent of disease"),
      qx = str_replace_all(qx, fixd("for response"), "extent of disease"),
      qx = str_replace_all(qx, regx("(^|\\s)staging"), "\\1extent of disease evaluation"),
      
      qx = str_replace_all(qx, regx("(^|\\s)transaminitis"), "\\1elevated liver enzymes"),
      qx = str_replace_all(qx, regx("desat($|\\s|[\\p{P}\\p{S}])"), "desaturation\\1"),
      qx = str_replace_all(qx, regx("perf($|\\s|[\\p{P}\\p{S}])"), "perforation\\1"),
      qx = str_replace_all(qx, regx("(^|\\s)lfts?($|\\s|[\\p{P}\\p{S}])"), "\\1liver function tests\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)SBO($|\\s|[\\p{P}\\p{S}])"), "\\1small bowel obstruction\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)LBO($|\\s|[\\p{P}\\p{S}])"), "\\1large bowel obstruction\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)fx($|\\s|[\\p{P}\\p{S}])"), "\\1fracture\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)pna($|\\s|[\\p{P}\\p{S}])"), "\\1pneumonia\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)NGT($|\\s|[\\p{P}\\p{S}])"), "\\1nasogastric tube\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)ptx($|\\s|[\\p{P}\\p{S}])"), "\\1pneumothorax\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)sob($|\\s|[\\p{P}\\p{S}])"), "\\1shortness of breath\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)PE($|\\s|[\\p{P}\\p{S}])"), "\\1pulmonary embolism\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)CKI($|\\s|[\\p{P}\\p{S}])"), "\\1chronic kidney injury\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)AKI($|\\s|[\\p{P}\\p{S}])"), "\\1acute kidney injury\\2"),
      
      qx = str_replace_all(qx, regx("(^|\\s)LUE($|\\s|[\\p{P}\\p{S}])"), "\\1left arm\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)RUE($|\\s|[\\p{P}\\p{S}])"), "\\1right arm\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)BLE($|\\s|[\\p{P}\\p{S}])"), "\\1bilateral legs\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)LLE($|\\s|[\\p{P}\\p{S}])"), "\\1left leg\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)RLE($|\\s|[\\p{P}\\p{S}])"), "\\1right leg\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)LUQ($|\\s|[\\p{P}\\p{S}])"), "\\1left upper quadrant\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)RUQ($|\\s|[\\p{P}\\p{S}])"), "\\1right upper quadrant\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)LLQ($|\\s|[\\p{P}\\p{S}])"), "\\1left lower quadrant\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)RLQ($|\\s|[\\p{P}\\p{S}])"), "\\1right lower quadrant\\2"),
      qx = str_replace_all(qx, fixd("LE edema"), "leg edema"),
      qx = str_replace_all(qx, fixd("UE edema"), "arm edema"),
      qx = str_replace_all(qx, fixd("LE swelling"), "leg swelling"),
      qx = str_replace_all(qx, fixd("UE swelling"), "arm swelling"),
      
      qx = str_replace_all(qx, regx("(^|\\s)abd(\\s|[\\p{P}\\p{S}])"), "\\1abdominal\\2"),
      
      qx = str_replace_all(qx, regx("(^|\\s)mets($|\\s|[\\p{P}\\p{S}])"), "\\1metastases\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)met($|\\s|[\\p{P}\\p{S}])"), "\\1metast.\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)met($|\\s|[\\p{P}\\p{S}])"), "\\1metast.\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)Gb($|\\s|[\\p{P}\\p{S}])"), "\\1Gallbladder\\2"),
      ds = str_replace_all(ds, regx("(^|\\s)Nhl($|\\s|[\\p{P}\\p{S}])"), "\\1Non-Hodgkin Lymphoma\\2"),
      
      qx = str_replace_all(qx, regx("(^|\\s)eval($|\\s|[\\p{P}\\p{S}])"), "\\1Evaluate\\2"),
      qx = str_replace_all(qx, regx("(^|\\s|[\\p{P}\\p{S}])R o(\\s|[\\p{P}\\p{S}])"), "\\1Evaluate for\\2"),
      qx = str_replace_all(qx, regx("(^|\\s|[\\p{P}\\p{S}])R(\\s|[\\p{P}\\p{S}])o$"), "\\1evaluation\\2"),
      qx = str_replace_all(qx, fixd("(^|\\s)rule\\sout($|\\s|[\\p{P}\\p{S}])"), "\\1Evaluate for\\2"),
      qx = str_replace_all(qx, regx("(^|\\s|[\\p{P}\\p{S}])s(\\s|[\\p{P}\\p{S}])p(\\s|[\\p{P}\\p{S}])"), "\\1post \\3"),
      ds = str_replace_all(ds, regx("(^|\\s|[\\p{P}\\p{S}])s(\\s|[\\p{P}\\p{S}])p(\\s|[\\p{P}\\p{S}])"), "\\1post \\3"),
      qx = str_replace_all(qx, regx("(^|\\s)post\\sRT($|\\s|[\\p{P}\\p{S}])"), "\\1post radiotherapy\\2"),
      qx = str_replace_all(qx, regx("(^|\\s)SBRT($|\\s|[\\p{P}\\p{S}])"), "\\1stereotactic radiotherapy\\2"),
      qx = str_replace_all(qx, regx("\\slns($|\\s|[\\p{P}\\p{S}])"), " lymph nodes"),
      qx = str_replace_all(qx, regx("(^|\\s)Fh of"), "\\1Family history of"),
      qx = str_replace_all(qx, regx("(^|\\s)crt(\\s|[\\p{P}\\p{S}])"), "chemoradiation\\1"),
      qx = str_replace_all(qx, regx("(^|\\s)loc($|\\s|[\\p{P}\\p{S}])"), "localization\\1"),
      qx = str_replace_all(qx, regx("(^|\\s)WNL($|\\s|[\\p{P}\\p{S}])"), "\\1within normal limits\\2"),
      
      # ds = str_squish(str_to_sentence(ds)),
      # qx = str_squish(str_to_sentence(qx)),
      qx = DescTools::StrCap(qx),
      ds = DescTools::StrCap(ds),
      hx = if_else(substr(ds, 1, 5) == substr(qx, 1, 5), qx, paste0(ds, ". ", qx)),
      hx = str_replace(hx, regx("\\sPOD\\s?(\\d)"), "postoperative day \\1"),
      hx = str_replace(hx, regx("Eod$"), "Evaluate extent of disease"),
      hx = str_replace(hx, fixd("for pod"), "extent of disease"),
      hx = str_replace(hx, regx("(^|\\s)r\\so\\spod($|\\s|[\\p{P}\\p{S}])"), "\\1evaluate extent of disease\\2"),
      hx = str_replace(hx, regx("(^|\\s)POD$"), "\\1extent of disease"),
      hx = str_replace(hx, regx("(^|\\s)POD(\\s|[\\p{P}\\p{S}])"), "\\1progression of disease\\2"),
      hx = str_replace(hx, regx("Per protocol(.*)"), "Evaluate extent of disease per protocol"),
      hx = str_replace(hx, regx("Per \\d\\d(.*)"), "Evaluate extent of disease per protocol"),
      
      hx = str_replace_all(hx, regx("\\sca($|\\s|[\\p{P}\\p{S}])"), " cancer\\1"),
      hx = str_replace_all(hx, fixd(".."), "."),
      
      hx = str_replace_all(hx, regx("(^|\\s)l\\s"), " left "),
      hx = str_replace_all(hx, regx("(^|\\s)r\\s"), " right "),
      hx = str_replace_all(hx, regx("(^|\\s)b\\s"), " bilateral "),
      hx = str_replace_all(hx, fixd("bilateral cell lymphoma"), "B-cell lymphoma"),
      hx = str_replace_all(hx, fixd("L>R"), "left greater than right"),
      hx = str_replace_all(hx, fixd("R>L"), "right greater than left"),
      
      hx = str_replace_all(hx, regx("(^|\\s)panc($|\\s|[\\p{P}\\p{S}])"), "\\1pancreatic\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)pe($|\\s|[\\p{P}\\p{S}])"), "\\1pulmonary embolus\\2"),
      hx = str_replace(hx, regx("(^|\\s)Gist($|\\s|[\\p{P}\\p{S}])"), "\\1Gastrointenstinal stromal tumor\\2"),
      hx = str_replace(hx, regx("(^|\\s)Nsclc($|\\s|[\\p{P}\\p{S}])"), "\\1Lung cancer\\2"),
      hx = str_replace(hx, regx("(^|\\s)Sclc($|\\s|[\\p{P}\\p{S}])"), "\\1Lung cancer\\2"),
      hx = str_replace(hx, regx("(^|\\s)Nsgct($|\\s|[\\p{P}\\p{S}])"), "\\1Testicular cancer\\2"),
      hx = str_replace(hx, regx("(^|\\s)Net($|\\s|[\\p{P}\\p{S}])"), "\\1Neuroendocrine tumor\\2"),
      hx = str_replace(hx, regx("(^|\\s)Rcc($|\\s|[\\p{P}\\p{S}])"), "\\1Renal cancer\\2"),
      hx = str_replace(hx, regx("(^|\\s)Hcc($|\\s|[\\p{P}\\p{S}])"), "\\1Hepatocellular carcinoma\\2"),
      hx = str_replace(hx, regx("(^|\\s)Pvns($|\\s|[\\p{P}\\p{S}])"), "\\1Pigmented villonodular synovitis\\2"),
      hx = str_replace(hx, regx("(^|\\s)pdac($|\\s|[\\p{P}\\p{S}])"), "\\1pancreatic cancer\\2"),
      hx = str_replace(hx, regx("(^|\\s)met($|\\s|[\\p{P}\\p{S}])"), "\\1metastasis\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)DJD($|\\s|[\\p{P}\\p{S}])"), "\\1degenerative joint changes\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)DDLS($|\\s|[\\p{P}\\p{S}])"), "\\1dedifferentiated liposarcoma\\2"),
      
      hx = str_replace(hx, regx("(^|\\s)dvts?($|\\s|[\\p{P}\\p{S}])"), "\\1Deep venous thrombosis\\2"),
      hx = str_replace(hx, regx("(^|\\s)Fap(\\s|[\\p{P}\\p{S}])"), "\\1Familial adenomatous polyposis\\2"),
      hx = str_replace(hx, regx("(^|\\s)Nhl(\\s|[\\p{P}\\p{S}])"), "\\1Lymphoma\\2"),
      hx = str_replace(hx, regx("(^|\\s)SLNB(\\s|[\\p{P}\\p{S}])"), "\\1Sentinel lymph node biopsy\\2"),
      hx = str_replace(hx, regx("(^|\\s)CLND(\\s|[\\p{P}\\p{S}])"), "\\1Complete lymph node dissection\\2"),
      hx = str_replace(hx, regx("(^|\\s)Mds(\\s|[\\p{P}\\p{S}])"), "\\1Myelodysplastic syndrome\\2"),
      hx = str_replace(hx, regx("(^|\\s)Aml(\\s|[\\p{P}\\p{S}])"), "\\1Acute myeloid leukemia\\2"),
      hx = str_replace(hx, regx("(^|\\s)All(\\s|[\\p{P}\\p{S}])"), "\\1Acute lymphocytic leukemia\\2"),
      hx = str_replace(hx, regx("(^|\\s)Cll(\\s|[\\p{P}\\p{S}])"), "\\1Chronic lymphocytic leukemia\\2"),
      hx = str_replace(hx, regx("(^|\\s)Dlbcl(\\s|[\\p{P}\\p{S}])"), "\\1Diffuse large B-cell lymphoma\\2"),
      hx = str_replace(hx, regx("(^|\\s)PSA($|\\s|[\\p{P}\\p{S}])"), " \\1PSA\\2"),
      hx = str_replace(hx, regx("(^|\\s)GIST($|\\s|[\\p{P}\\p{S}])"), " \\1Gastrointestinal stromal tumor\\2"),
      hx = str_replace(hx, regx("(^|\\s)XGP($|\\s|[\\p{P}\\p{S}])"), "\\1Xanthogranulomatous pyelonephritis\\2"),
      hx = str_replace(hx, regx("(^|\\s)pnet($|\\s|[\\p{P}\\p{S}])"), "\\1Pancreatic neuroendocrine tumor\\2"),
      hx = str_replace(hx, regx("(^|\\s)Hodgkin s($|\\s|[\\p{P}\\p{S}])"), "\\1Hodgkin\\2"),
      hx = str_replace(hx, regx("(^|\\s)Scc($|\\s|[\\p{P}\\p{S}])"), "\\1Squamous cell cancer\\2"),
      hx = str_replace(hx, fixd("cancer tumor"), "cancer"),
      hx = str_replace(hx, fixd("Head neck cancer"), "Head and neck cancer"),
      hx = str_replace_all(hx, regx("(^|\\s)ipmn($|\\s|[\\p{P}\\p{S}])"), "\\1IPMN\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)Mgus($|\\s|[\\p{P}\\p{S}])"), "\\1MGUS\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)psa($|\\s|[\\p{P}\\p{S}])"), "\\1PSA\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)gi($|\\s|[\\p{P}\\p{S}])"), "\\1GI\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)ij($|\\s|[\\p{P}\\p{S}])"), "\\1internal jugular\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)Nf($|\\s|[\\p{P}\\p{S}])"), "\\1Neurofibromatosis\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)nf1($|\\s|[\\p{P}\\p{S}])"), "\\1Neurofibromatosis Type 1\\2"),
      hx = str_replace_all(hx, regx("(^|\\s)nf-1($|\\s|[\\p{P}\\p{S}])"), "\\1Neurofibromatosis Type 1\\2"),
      
      hx = str_replace(hx, fixd(" nos."), "."),
      hx = str_replace(hx, fixd(" . "), ". "),
      hx = str_replace(hx, fixd(";."), "."),
      hx = str_remove(hx, regx(" \\.$")),
      hx = str_remove(hx, regx("; \\(cs: cat \\w*\\)")),
      hx = str_remove(hx, regx("(^|\\s):")),
      hx = str_remove(hx, regx("^\\s?\\.\\s?")),
      hx = str_squish(hx),
      
      hx = if_else(str_detect(hx, fixd("thyroid")), str_replace(hx, regx("(^|\\s)ptc($|\\s|[\\p{P}\\p{S}])"), "\\1papillary thyroid cancer\\2"), hx),
      hx = if_else(str_detect(hx, fixd("testicular")), str_replace(hx, regx("(^|\\s)gct($|\\s|[\\p{P}\\p{S}])"), "\\1germ cell tumor\\2"), hx),
      hx = if_else(str_detect(hx, regex("([A-Z]){2}")), hx, str_to_sentence(hx)),
      hx = paste0(hx, "."),
      hx = str_replace(hx, fixd(";."), "."),
      hx = str_replace(hx, fixd(".."), ".")
    )
}

